# Generated by Django 4.1.6 on 2023-02-07 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=20)),
                ('station_name', models.CharField(max_length=20)),
                ('avg_max_temp', models.IntegerField()),
                ('avg_min_temp', models.IntegerField()),
                ('total_acc_ppt', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=20)),
                ('max_temp', models.IntegerField()),
                ('min_temp', models.IntegerField()),
                ('precipitation', models.IntegerField()),
                ('station_name', models.CharField(max_length=20)),
            ],
            options={
                'unique_together': {('date', 'station_name')},
            },
        ),
    ]
