# Generated by Django 4.1.6 on 2023-02-07 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather_app', '0002_alter_weather_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='weather',
            unique_together={('date', 'station_name')},
        ),
    ]
